# Site settings
title: Sparks
email: sparksvann@gmail.com
description: coding monkey
whatsup: >
        The days were slipping past that the good things never last
avatar: avatar.jpg
name: SparksVann
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github: https://github.com/SparksFyz
github_username:  Sparksfyz
permalink: /:year/:month/:day/:title/

#url settings
homepage: http://SparksFyz.github.io/
assets: /static/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
highlighter: pygments
# highlighter: rouge
# highlighter: false

# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#assets
project:
  cloudseu: /static/image/cloudseu.png
  herald1: /static/image/herald1.jpg
  herald2: /static/image/herald2.jpg
  herald3: /static/image/herald3.jpg